server:
  port: 8080

curso:
  nome-app: Sistema de Chamados
  mensagem: Ambiente padrão

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chamados
    username: curso
    password: curso
  jpa:
    hibernate:
      ddl-auto: validate   # o Hibernate confere; quem cria e evolui é o Flyway
    show-sql: true
